apps/users/urls.py
#!/user/bin/env python3
"""@File: <filename>.py
@Version: 0.3.0 to 0.3.0.?
@Desc: apps | <app> |  <module>
@Author: Charles Fowler
@Copyright: 2023
@Date Created: 23/09/?
@Date Modified: 23/09/??
@Python Version: 3.11.04
@Django Version: 4.2.3/.04/.05
@Notes / Ideas v Implement:
- .
@Changelog:
- Added:
- added: Created initial file: 23/09/??:
- Updated:
- updated:
@Plan:
- TODO:
- FIXME:
- CHECK:
    - DONE: PylInt: 23/09/30
"""
from django.urls import path

from apps.users import views


# Namespace for URL Patterns: users:route_link_reference
app_name = 'users'  # pylint: disable=invalid-name
"""
#    URLPatterns - Handles AllAuth
    - AllAuth Views/Templates: users.urls | kore.views
"""

urlpatterns = [
    path('login/', views.DashLoginView.as_view(), name='account_login'),
    path('signup/', views.DashSignupView.as_view(), name='account_signup'),
    path('logout/', views.DashLogoutView.as_view(), name='account_logout'),
    path(
        'confirm-email/<str:key>/',
        views.DashConfirmEmailView.as_view(),
        name='account_confirm_email',
    ),
    # path(
    #     "confirm-email/",
    #     views.email_verification_sent,
    #     name="account_email_verification_sent",
    # ),
    # including allauth urls
    # Other views@
    # 1) Password reset
    # 2) Password change & set
    # 3) Email change
    # 4) Account management
]

dash_and_do/urls.py
#  Copyright (c) 2023.

# ================== URL Patterns ==================
# Changed 2023-08-15
# added: URL + includes for DEV when Admin enabled
# added: URL + includes for Debug Toolbar when Admin enabled
# added: URL + includes for Admin Password reset when Admin enabled
# added: URL + includes for Admin Docs when Admin enabled
# Changed 2023-08-16:
# added: URL + includes for AllAuth for profile & Commented Out
# added: URL + includes for Accounts for profile & Commented Out
# added: URL + includes for Dash profile & Commented Out
# noted : Progressive enablement of Accounts, Dash, AllAuth
# Noted: that you do not need the URLs provided by django.contrib.auth.urls
# Noted: can use the URLs provided by allauth:
#  - account_login,
#  - account_logout,
#  - account_set_password
# Changed 2023-08-24:
# added: SiteMap in Comments as a Planner
# added: Core index forms to kore.urls
from django.conf import settings
from django.urls import include
from django.urls import path

urlpatterns = [] # Base variable defintion

if settings.DEBUG:
    # import debug_toolbar
    urlpatterns = [
    ]

urlpatterns += [
    # path('__debug__/', include(debug_toolbar.urls)),
    # path('admin/', admin.site.urls),
    path('', include('apps.kore.urls', namespace='kore')),
    path('', include('apps.users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
]
# path('profile/', include('profile.urls', namespace='profile')),
# path('profile/', include('allauth.urls', namespace='profile')),
# path('dash/', include('dash.urls', namespace='dash'))

apps/users/models.py
#!/user/bin/env python3
"""@File: <filename>.py
@Version: 0.3.0 to 0.3.0.?
@Desc: apps | <app> |  <module>
@Author: Charles Fowler
@Copyright: 2023
@Date Created: 23/09/?
@Date Modified: 23/09/??
@Python Version: 3.11.04
@Django Version: 4.2.3/.04/.05
@Notes / Ideas v Implement:
-  Option 3: A Custom User Model
Subsisitute the default User model by subclassing AbstractBaseUser
Defaul fields not preserved by subclassing:
Impacts existing methods
Entire new User Model, Update of settings .py
App has specif requirements (like using AllAuth)
Flex to use email as id token, not username,
Pro: most freedome, cons: most work
@Changelog:
- Added:
- added: Created initial file: 23/09/?24
- added: Added User Model: 23/09/24
- added: Added UserManager: 23/09/24
- Updated: User Model additional methods: 23/11/01
- updated:
@Plan:
- TODO:
- FIXME:
- CHECK:
  - DONE: Pylint: 10/10, 23/09/30
"""

# https://medium.com/
# @ksarthak4ever/django-custom-user-model-allauth-for(-oauth-20)c84888c3184
# OopCompanion:suppressRename

from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.utils import timezone

from apps.users.managers import DashUserManager


class DashUser(AbstractBaseUser, PermissionsMixin):
    """Credit:
    - Author: Sarthak Kumar(@ksarthak4ever)
    - Title: Django Custom User Model + Allauth for OAuth
    - Date Created: 2019-04-02
    - URL: https://medium.com/
    - USER: @ksarthak4ever/
    - SLUG: django-custom-user-model-allauth-for-oauth-20c84888c3184
    - Last Accessed: 2023-09-24
    :class: DashUser: Custom User Model, subclasses: AbstractBaseUser
    :param email:
    :param name:
    :param is_staff: required by admin
    :param is_superuser: PermissionsMixin to grant all permissions
    :param is_active: user active?
    :param last_login:
    :param date_joined:
    :param USERNAME_FIELD: unique id, i.e email
    :param EMAIL_FIELD: re get_email_field_name()
    :param REQUIRED_FIELDS: list of required fields on sigh up
    :param objects: User Manager
    :return: User
    :rtype: User.
    """

    class Meta:  # pylint: disable=R0903
        """Meta definition for DashUser."""
        db_table = 'dashuser'  # optional, name of the table in db
        app_label = 'users'
        verbose_name = 'DashUser'

    email = models.EmailField(max_length=50,
                              null=False,
                              blank=False,
                              unique=True,
                              default='')
    name = models.CharField(max_length=50,
                            null=True,
                            blank=True,
                            default='')
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    last_login = models.DateTimeField(null=True,
                                      blank=True,
                                      default=timezone.now)
    date_joined = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = DashUserManager()

    def get_absolute_url(self):
        """Return the absolute URL for the DashUser instance.

        :return: The absolute URL for the DashUser instance.
        """
        return f'/users/{self.pk}/'

    def __str__(self):
        """Return the string representation of the DashUser instance."""
        return f'{self.name} ({self.email})' \
            if self.name else self.email or 'No email'

    def get_full_name(self):
        """ Returns the full name (email) of the user.

        :param self: DashUser: The instance of the `DashUser` class.
        :return: The full name of the user.
        :rtype: str
        """
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        """ Return the short name (email) of the user.

            :param self: DashUser: The instance of the `DashUser` class.
            :return: The short name of the user.
            :rtype: str
        """
        # The user is identified by their email address
        return self.email

    # noinspection PyUnusedFunction
    def has_perm(self, perm, obj=None):
        """Does the user have a specific permission?"""
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        """Does the user have permissions to view the app `app_label`?"""
        # Simplest possible answer: Yes, always
        return True

    # noinspection PyUnusedFunction
    @property
    def is_a_staff(self):
        """Is the user a member of staff?"""
        return self.is_staff

    # noinspection PyUnusedFunction
    @property
    def is_a_super(self):
        """Is the user a admin member?"""
        return self.is_superuser

apps/users/views.py
#!/user/bin/env python3
# pylint: disable=R0901
"""@File: <filename>.py
@Version: 0.3.0 to 0.3.0.?
@Desc: apps | <app> |  <module>
@Author: Charles Fowler
@Copyright: 2023
@Date Created: 23/09/?
@Date Modified: 23/09/??
@Python Version: 3.11.04
@Django Version: 4.2.3/.04/.05
@Notes / Ideas v Implement:
- .
@Changelog:
- Added:
- added: Created initial file: 23/09/26:
- Updated:
- updated:
@Plan:
- TODO:
- FIXME:
- CHECK:
    - DONE: PyLint 2023/09/30
    - IGNORE: PyLint R0901,R0903
"""
import logging

from allauth.account.utils import passthrough_next_redirect_url
# OopCompanion:suppressRename
# AllAuth Libraries
from allauth.account.views import ConfirmEmailView
from allauth.account.views import LoginView
from allauth.account.views import LogoutView
from allauth.account.views import SignupView
from allauth.core.exceptions import ImmediateHttpResponse
# Django Libraries
from django.contrib import messages
from django.http import HttpResponse
from django.http import HttpResponseRedirect
# from django.middleware.csrf import get_token
from django.shortcuts import render
from django.template.loader import render_to_string
from django.template.response import TemplateResponse
from django.urls import reverse, reverse_lazy

# Local Libraries: Users
from apps.users.debugg import DebugAdapter as Debugg
# Local Libraries
from apps.users.forms import DashLoginForm
from apps.users.forms import DashSignupForm
from apps.users.helpers import get_last_status
from apps.users.sessions import DashUserSession
from apps.users.values import SiteContext
from dash_and_do.htmx import hx_redirect_success
from dash_and_do.settings import DEBUG
from dash_and_do.settings import LOGIN_REDIRECT_URL
from dash_and_do.settings import LOGOUT_REDIRECT_URL
# from dash_and_do.settings import SESSION_COOKIE_AGE as DEFAULT_SESSION_AGE
# Local Libraries: Dash and Do
from dash_and_do.utils import get_date


# from django.utils.decorators import method_decorator
# from django.views.decorators.csrf import ensure_csrf_cookie


debugr = Debugg()


class FormViews:  # pylint: disable=too-few-public-methods
    """Form Values: Strings."""
    DEFAULT_FORM_KEY = 'form'
    INDEX_REVERSE = 'kore:index'
    VERIFY_REVERSE = 'kore:verify'
    PRIVATE_REVERSE = 'kore:private'
    CONFIRM_REVERSE = 'kore:confirm'
    TOGGLE_FRIENDLY = False
    TOGGLE_ERROR = True


    class Login:  # pylint: disable=too-few-public-methods
        """Constants Class for Login FormView."""
        VIEWNAME = 'DashLoginView'
        CTXNAME = 'login_form'
        TEMPLATE = 'forms/form_login.html'
        PREFIX = 'current'
        REMEMBER = 'remember'


    class Signup:  # pylint: disable=too-few-public-methods
        """Constants Class for Signup FormView."""
        VIEWNAME = 'DashSignupView'
        CTXNAME = 'signup_form'
        TEMPLATE = 'verify.html'
        SIGNUP_KEY = 'signup_url'
        SIGNUP_URL = 'users:account_signup'
        SUCCESS_URL = 'verify.html'
        CONFIRM_URL = 'account_confirm_email.html'
        PREXIX_KEY = 'prefix'
        PREFIX_UNBOUND = 'new'
        PREFIX_BOUND = 'data'
        SUCCESS_MESSAGE = ('Please check your email to '
                           'activate your account.')
        UNEXPECTED_FRIENDLY = ('An unexpected issue occurred during '
                               'registration. Please try again later.')


    # noinspection PyUnusedClass
    class Confirm:  # pylint: disable=too-few-public-methods
        """Constants Class for Signup FormView."""
        CTXNAME = 'confirm_view'
        TEMPLATE = 'confirm.html'
        PREFIX = 'confirm'
        EMAIL_CTXKEY = 'email'
        IS_CTXCONFIRM = 'can_confirm'


    class LogoutView:  # pylint: disable=too-few-public-methods
        """Constants Class for LogoutView."""
        TEMPLATE = 'account/logout.html'


class SessionVals:
    """The SessionVals class: Set of constants/flags used for session values.

    Attributes:
        VALID (bool): Represents a valid session value.
        INVALID (bool): Represents an invalid session value.
        CONFIRMED (bool): Represents a confirmed session value.
        NOTCONFIRM (bool): Represents a not confirmed session value.
        VERIFIED (bool): Represents a verified session value.
    NOTVERIFIED (bool): Represents a not verified session value.
    """
    VALID = True
    INVALID = False
    CONFIRMED = True
    NOTCONFIRM = False
    VERIFIED = True
    NOTVERIFIED = False
    # If "remember" is not set, expire the session
    # hen the user closes their browser.
    EXPIRE_NOT_SET = -1
    REMEMBER = 60 * 60 * 24 * 7 * 2
    BROWSER_CLOSE = 0


# noinspection PyUnusedClass
class HTTP:  # pylint: disable=too-few-public-methods # noinspection
    """HTTP Headers: Strings."""

    REDIRECTS = True
    REDIRECTS_OFF = False


    # noinspection PyUnusedClass
    class Headers:  # pylint: disable=too-few-public-methods
        """HTTP Headers: Strings."""
        HX_REDIRECT = 'HX-Redirect'
        HTTP_LOCATION = 'Location'
        HX_CONTENT_TYPE = 'Content-Type'
        HX_CONTENT_FORMAT = 'text/html'


    # noinspection PyUnusedClass
    class Methods:  # noinspection
        """HTTP Methods: Strings."""
        GET = 'GET'
        POST = 'POST'
        PUT = 'PUT'


logger = logging.getLogger(__name__)
sitecontext = SiteContext()


def log_template(view, request, context, template,
                 exec=False, trace=True, level=1):
    """Log Template."""
    logger = logging.getLogger('django.template')
    logger.debug(view,
                 exc_info=exec,
                 stack_info=trace,
                 stacklevel=level,
                 extra={'request': request,
                        'template': template,
                        'context': context})


class DashSignupView(SignupView):
    """DashSignupView class is a custom implementation of the SignupView class
    from the allauth library.

    It provides functionality for user signup and
    handles the form validation and submission.

    Attributes:
    :param: template_name: The path to the template file for
                rendering the signup view.
    :param: success_url: The URL where the user will be redirected
                after successful signup.
    :param: form_class: A class representing the form used for user signup.

    Methods:
    :method: post
            It handles the form submission and validation.
            If the form is valid, it redirects the user to the success URL.
            If the form is invalid, it re-renders the form with error messages.
    :method: form_valid:
            It is called when the form is valid.
            It performs custom logic before saving the user instance.
            It sets the email and verification flags in the user session.
            It also sends a success message to the user.
            Finally, it redirects the user to the success URL
            using the `hx_redirect_success` function.
    :method: form_invalid:
            It is called when the form is invalid.
            It raises an ImmediateHttpResponse with the rendered
            form HTML to be handled by HTMX.
    :method: get_context_data
            It retrieves additional context data for the template rendering,
             including the session data and the latest status.
    :method: get_success_url:
            Returns the success URL for the user after successful signup.

    Note: This class relies on other imported modules and classes such as
    ConfirmEmailView, LoginView, LogoutView, ImmediateHttpResponse,
    hx_redirect_success, is_htmx, LOGIN_REDIRECT_URL, LOGOUT_REDIRECT_URL,
    messages, HttpResponse, HttpResponseRedirect, render, render_to_string,
    reverse_lazy, DebugAdapter, get_last_status, and DashUserSession.
    """

    template_name = FormViews.Signup.TEMPLATE  # specify your own template
    success_url = reverse_lazy(FormViews.VERIFY_REVERSE)
    form_class = DashSignupForm  # Custom AllAuth Signup Form

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.logger = None
        self.setlog('django.request')

    def get(self, request, *args, **kwargs):
        signup = self.form_class()  # signup is the labeled form instance
        self.log(FormViews.Signup.VIEWNAME, self.request,
                 signup, 'GET')
        return render(request,
                      self.template_name,
                      {'signup_form': signup})

    def post(self, request, *args, **kwargs):
        """Post method for the SignupView class.

        :param request: The HTTP request object.
        :param args: Additional positional arguments.
        :param kwargs: Additional keyword arguments.
        :return: An HTTP response | HTTP Redirect object(s).
        """
        # Validate the form.
        super().post(request, *args, **kwargs)
        signup = self.get_form()  # signup is the labeled form instance
        # Check if form is valid, redirect to success_url
        if signup.is_valid():
            # Redirect on valid.
            return HttpResponseRedirect(self.get_success_url())
        else:
            # If form is not valid, re-render the form with error messages
            signup_context = {FormViews.Signup.CTXNAME: signup}
            return TemplateResponse(request, FormViews.Signup.TEMPLATE,
                                    signup_context, content_type='text/html')

    def form_valid(self, form):
        """If the form is valid, redirect to the supplied URL."""
        # Here you can add your custom logic before the user instance is saved
        # handle validation here...
        # ??
        # Call the parent class's method to handle the saving and redirection
        # logic
        # Call the parent class's method to handle the saving and redirection
        # logic
        response = super().form_valid(form)
        # For example, if you want to send a custom success message:

apps/users/templates/users/account/account_inactive.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Account Inactive" %}{% endblock head_title %}

{% block content %}
<h1>{% trans "Account Inactive" %}</h1>

<p>{% trans "This account is inactive." %}</p>
{% endblock content %}

apps/users/templates/users/account/email_change.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Email Address" %}
{% endblock head_title %}
{% block content %}
    <h1>{% trans "Email Address" %}</h1>
    {% if emailaddresses %}
        {% if current_emailaddress %}
            <p>
                {% trans 'The following email address is associated with your account:' %} <a href="mailto:{{ current_emailaddress.email }}">{{ current_emailaddress.email }}</a>
            </p>
        {% endif %}
        {% if new_emailaddress %}
            <p>
                {% trans 'Your email address is still pending verification:' %} <a href="mailto:{{ new_emailaddress.email }}">{{ new_emailaddress.email }}</a>
            </p>
            <form method="post" action="{% url 'account_email' %}">
                {% csrf_token %}
                <input type="hidden" name="email" value="{{ new_emailaddress.email }}">
                <button type="submit" name="action_send">{% trans 'Re-send Verification' %}</button>
            </form>
        {% endif %}
    {% else %}
        {% include "account/snippets/warn_no_email.html" %}
    {% endif %}
    <h2>{% trans "Change Email Address" %}</h2>
    <form method="post" action="{% url 'account_email' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="action_add" type="submit">{% trans "Change Email" %}</button>
    </form>
{% endblock content %}

apps/users/templates/users/account/email_confirm.html
{% extends "account/base.html" %}

{% load i18n %}
{% load account %}

{% block head_title %}{% trans "Confirm Email Address" %}{% endblock head_title %}


{% block content %}
<h1>{% trans "Confirm Email Address" %}</h1>

{% if confirmation %}

{% user_display confirmation.email_address.user as user_display %}

{% if can_confirm %}
<p>{% blocktrans with confirmation.email_address.email as email %}Please confirm that <a href="mailto:{{ email }}">{{ email }}</a> is an email address for user {{ user_display }}.{% endblocktrans %}</p>

<form method="post" action="{% url 'users:account_confirm_email' confirmation.key %}">
{% csrf_token %}
    <button type="submit">{% trans 'Confirm' %}</button>
</form>
{% else %}
<p>{% blocktrans %}Unable to confirm {{ email }} because it is already confirmed by a different account.{% endblocktrans %}</p>
{% endif %}

{% else %}

{% url 'account_email' as email_url %}

<p>{% blocktrans %}This email confirmation link expired or is invalid. Please <a href="{{ email_url }}">issue a new email confirmation request</a>.{% endblocktrans %}</p>

{% endif %}

{% endblock content %}

apps/users/templates/users/account/login.html
{% load i18n %}
{#{% load account socialaccount %}#}

{#{% block head_title %}{% trans "Sign In" %}{% endblock head_title %}#}

{% block form_login %}

    {#<h1>{% trans "Sign In" %}</h1>#}

    {#{% get_providers as socialaccount_providers %}#}

    {#{% if socialaccount_providers %}#}
    {#<p>{% blocktrans with site.name as site_name %}Please sign in with one#}
    {#of your existing third party accounts. Or, <a href="{{ signup_url }}">sign up</a>#}
    {#for a {{ site_name }} account and sign in below:{% endblocktrans %}</p>#}

    {#<div class="socialaccount_ballot">#}
    {##}
    {#  <ul class="socialaccount_providers">#}
    {#    {% include "socialaccount/snippets/provider_list.html" with process="login" %}#}
    {#  </ul>#}
    {##}
    {#  <div class="login-or">{% trans 'or' %}</div>#}
    {##}
    {#</div>#}

    {#{% include "socialaccount/snippets/login_extra.html" %}#}

    {#{% else %}#}
    {#<p>{% blocktrans %}If you have not created an account yet, then please#}
    {#<a href="{{ signup_url }}">sign up</a> first.{% endblocktrans %}</p>#}
    {#{% endif %}#}
    {% if login_form %}
        <form
            class="[ form-login ]"
            action="{% url 'users:account_login' %}"
            data-form="login"
            data-view="public"
            id="login-form"
            method="post"
            name="login-form"
            hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
            hx-post="{% url 'users:account_login' %}"
            hx-trigger="submit"
            hx-swap="outerHTML">
            {% csrf_token %}
            {% with loginerr=login_form.non_field_errors %}
                {% if loginerr %}
                    {% for formerror in loginerr %}
                        {{ formerror.errors }}
                        {{ formerror }}
                    {% endfor %}
                {% endif %}
            {% endwith %}
            <!-- ======================= PUBLIC LOGIN FIELDS' 1 COLUMN ===================  -->
            {% if redirect_field_value %}
                <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
            {% endif %}
            <input type="hidden" name="next" value="{{ login_form.prefix }}" />
            <fieldset
                class="[ form-card ] [ w-full h-full ] [ p-4 border ] [ bg-gray-100 ] [ rounded-lg ]"
                data-menu="card"
                data-view="public"
                form="login-form"
                id="fields-login-form"
                name="login-form">
                <legend
                    class="[ form-card-label ] [ sr-only ]"
                    aria-description="Login Form Card | Username | Password | Remember-me Checkbox | Login button"
                    hidden="until-found"
                    id="label-login-form">
                    Login Form
                </legend>
                <!-- ========================= PUBLIC LOGIN ROW========================= -->
                <div
                    class="[ formrow ] [ relative ] [ my-4 ]"
                    aria-description="Login Menu Item: Username"
                    data-view="public"
                    id="login-user-row">

                    <input
                        class="[ input-field peer ] [ w-full h-10 ] [ mb-4 ] [ border p-2 ] [ rounded-md ] [ text-start gray-900 ] [ placeholder-transparent ] | [ valid:bg-green-100 invalid:bg-red-100 :invalid:bg-white-100 ] [ focus:outline-none focus:border-rose-600 ] [ focus:not(:placeholder-shown) ]"
                        id="login-username"
                        aria-description="Enter Username: Input Length: min: 6, max: 30"
                        autocomplete="username"
                        data-view="public"
                        maxlength="30"
                        minlength="6"
                        name="username"
                        placeholder="Username"
                        required
                        tabindex="2"
                        title="Enter a valid Username"
                        type="text" />
                    <label
                        class="[ input-label ] [ w-full ] [ absolute -top-[5] left-1 ] [ text-start text-gray-500 ] | [ peer-placeholder-shown:text-base ] [ peer-placeholder-shown:text-gray-400 ] [ peer-placeholder-shown:top-2 ] | [ peer-focus:-top-4 peer-focus:text-gray-600 peer-focus:text-sm ] [ transition-all duration-300 ease-in-out ]"
                        id="login-username-tag"
                        aria-description="Enter account username"
                        aria-labelledby="login-username"
                        data-view="public"
                        for="login-username">
                        Username
                    </label>
                    {% if login_form.email.errors %}
                        {% for error in login_form.email.errors %}
                            <span class="[ input-message ] [ text-red-600 text-xs ]"
                                  data-status="invalid"
                                  data-view="public"
                                  id="invalid-signupmatch-msg">
                            {{ error }}
                        </span>
                        {% endfor %}
                    {% endif %}
                </div>
                <!-- ========================= PUBLIC LOGIN ROW========================= -->
                <div
                    class="[ form-group ] [ relative ] [ my-4 ]"
                    data-view="public"
                    id="login-pass-row">
                    <!-- TODO:  pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@$!%*?&]).{12,}" -->
                    <!-- TODO:  pattern="/^[a-zA-Z0-9@#$%^&*]{8,}$/" -->
                    <input
                        class="[ input-field peer ] [ w-full h-10 ] [ mb-4 ] [ border p-2 ] [ rounded-md ] [ text-start gray-900 ] [ placeholder-transparent ] | [ valid:bg-green-100 invalid:bg-red-100 :invalid:bg-white-100 ] [ focus:outline-none focus:border-rose-600 ] [ focus:not(:placeholder-shown) ]"
                        id="login-password"
                        aria-description="Passwords using a-zA-Z0-9 and sumbols"
                        aria-label="Enter a password"
                        autocomplete="current-password"
                        data-view="public"
                        name="password"
                        placeholder="Password"
                        required
                        title="Enter a valid Password"
                        type="password" />
                    <label
                        class="[ input-label ] [ w-full ] [ absolute -top-[5] left-1 ] [ text-start text-gray-500 ] | [ peer-placeholder-shown:text-base ] [ peer-placeholder-shown:text-gray-400 ] [ peer-placeholder-shown:top-2 ] | [ peer-focus:-top-4 peer-focus:text-gray-600 peer-focus:text-sm ] [ transition-all duration-300 ease-in-out ]"
                        id="login-password-tag"
                        aria-labelledby="login-password"
                        aria-description="Enter account password"
                        data-view="public"
                        for="login-password">
                        Password
                    </label>
                    {% if login_form.email.errors %}
                        {% for error in login_form.enterpassword.errors %}
                            <span class="[ input-message ] [ text-red-600 text-xs ]"
                                  data-status="invalid"
                                  data-view="public"
                                  id="invalid-signupmatch-msg">
                            {{ error }}
                        </span>
                        {% endfor %}
                    {% endif %}
                </div>
                <!-- ========================= PUBLIC LOGIN BUTTON ======================== -->
                <div
                    class="[ form-group ] [ flex flex-row ] [ justify-between items-center ] [ my-2 ]"
                    aria-description="Login Menu Item: Checkbox and Button"
                    data-view="public"
                    id="login-btn-row">
                    <!-- ========================= REMEMBER ME CHECKBOX ======================== -->
                    <div
                        class="[ flex flex-col ] [ items-center ]"
                        id="login-row-checkbox">
                        <input
                            class="[ input-field form-checkbox ] [ m-1 ] [ h-5 w-5 ] [ rounded-md ] [ text-blue-600 ] [ focus:ring-blue-500 ]"
                            aria-description="Remember login for next visit"
                            aria-label="Remember me checkbox"
                            id="remember-me"
                            name="remember-me"
                            value="remember"
                            type="checkbox" />
                        <label
                            class="[ text-sm text-gray-500 ]"
                            aria-labelledby="remember-me"
                            aria-description="Checkbox to remember login details"
                            for="remember-me">
                            Remember
                        </label>
                    </div>
                    <!-- ========================= PUBLIC LOGIN BUTTON ======================== -->
                    <div class="[ flex ] [ items-end ]">
                        <input
                            class="[ input-field peer ] [ block w-full ] [ mb-4 ] [ p-2 ] [ border rounded-md outline-none ] [ font-medium text-base text-gray-500 ] | [ focus:ring-blue-500 focus:border-blue-500 ]"
                            aria-description="Submit form to login and access account"
                            data-view="public"
                            type="submit"
                            value="Login" />
                    </div>
                </div>
                <!-- ========================= PUBLIC LOGIN ROW========================= -->
                <!-- ========================= FORGET PAGASSWORD: LINK ================= -->
                <!-- ========================= FORGET PAGASSWORD: Reset.html =========== -->
            </fieldset>
        </form>
    {% else %}
        {# This message should never display. #}
        <p> There has been an error. Contact the Site Adminiistrator</p>
    {% endif %}
{% endblock form_login %}

apps/users/templates/users/account/password_reset_from_key_done.html
{% extends "account/base.html" %}

{% load i18n %}
{% block head_title %}{% trans "Change Password" %}{% endblock head_title %}

{% block content %}
    <h1>{% trans "Change Password" %}</h1>
    <p>{% trans 'Your password is now changed.' %}</p>
{% endblock content %}